language: rust
rust:
    - stable
    - nightly
os:
  - linux
  - osx
env:
  global:
    - LD_LIBRARY_PATH: /usr/local/lib
    - secure: i8Ijk6g4/26e3e7+r2OeGAPSP8G8O9P50JibW1omJ0j0ixXhyhPoY2bch3CGhnOu44dI5O31IIbjJJ+iEMp29xQBvkv9YpxAI+hIzOP+XAH6GCYxUDiBVcDoWrXTj+wU6/veuvjLCunu4eRHlskrgJbZXhUVODYzJuLgsN8Ou0w=
script:
  - cargo build -v
  - cargo build -v --features rustc-serialize
  - cargo test -v
  - cargo test -v --features rustc-serialize
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      cargo build -v --features serde_support;
      cargo test -v --features serde_support;
    fi
  - cargo doc
after_script:
  - cd target && curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
