language: rust
sudo: false
rust:
  # 1.13.0 is the earliest version that Serde 1.0 tests, so we follow suit
  - 1.13.0
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
matrix:
  allow_failures:
    - rust: nightly
env:
  global:
    - LD_LIBRARY_PATH: /usr/local/lib
script: ./.travis.sh
notifications:
  email: false
  irc:
    channels:
      - "irc.mozilla.org#chronotope"
    template:
      - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
    skip_join: true
