environment:
  matrix:
    - TARGET: 1.13.0-x86_64-pc-windows-gnu
    - TARGET: nightly-x86_64-pc-windows-msvc
    - TARGET: nightly-i686-pc-windows-msvc
    - TARGET: nightly-x86_64-pc-windows-gnu
    - TARGET: nightly-i686-pc-windows-gnu
matrix:
  allow_failures:
    - channel: nightly
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:TARGET}.exe" -FileName "rust-install.exe"
  - ps: .\rust-install.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin"
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - sh -c 'PATH=`rustc --print sysroot`/bin:$PATH ./.travis.sh'
